services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ppya_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ppya
      POSTGRES_USER: ppya
      POSTGRES_PASSWORD: ppya
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
